# logging.level:
#   '[reactor.netty]': trace

spring:
  application.name: spring7gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      server:
        webflux:
          # httpclient.wiretap: true
          # httpserver.wiretap: true
          routes:
            - id: spring7restwebmvc
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/*
            - id: spring7reactive
              uri: http://localhost:8082
              predicates:
                - Path=/api/v2/*
            - id: spring7reactivemongo
              uri: http://localhost:8083
              predicates:
                - Path=/api/v3/*

management:
  endpoint.health.probes.enabled: true
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true
