spring.application.name: spring7gateway

# logging.level:
#   '[reactor.netty]': trace

spring:
  cloud:
    gateway:
      server:
        webflux:
          # httpclient.wiretap: true
          # httpserver.wiretap: true
          routes:
            - id: spring7restwebmvc
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/*
            - id: spring7reactive
              uri: http://localhost:8082
              predicates:
                - Path=/api/v2/*
            - id: spring7reactivemongo
              uri: http://localhost:8083
              predicates:
                - Path=/api/v3/*
